package payrollsystem;

/**
 *
 * @author Christian AUGUSTYN
 */
public class NewEmployeeEntry extends javax.swing.JDialog {
    private int daysWorked;
    private int hourlyRate;
    private int salary;

    /**
     * Creates new form NewEmployeeEntry2
     */
    public NewEmployeeEntry(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonAddEmployee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHourPerDay1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextFieldHourPerDay = new javax.swing.JTextField();
        jTextFieldHourPerDay2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxSaturday = new javax.swing.JCheckBox();
        jCheckBoxMonday = new javax.swing.JCheckBox();
        jCheckBoxThursday = new javax.swing.JCheckBox();
        jCheckBoxSaturday1 = new javax.swing.JCheckBox();
        jCheckBoxWednesday1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jCheckBoxWednesday = new javax.swing.JCheckBox();
        jCheckBoxFriday1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jCheckBoxTuesday = new javax.swing.JCheckBox();
        jCheckBoxTuesday1 = new javax.swing.JCheckBox();
        jCheckBoxSunday1 = new javax.swing.JCheckBox();
        jCheckBoxMonday1 = new javax.swing.JCheckBox();
        jCheckBoxFriday = new javax.swing.JCheckBox();
        jCheckBoxSunday = new javax.swing.JCheckBox();
        jCheckBoxThursday1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Employee");

        jLabel8.setText("Gross Salary");

        jTextField3.setText("jTextField3");

        jLabel10.setText("Net Salary");

        jLabel9.setText("Total Deduction");

        jButtonAddEmployee.setText("Add Employee");
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEmployeeActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee name:");

        jLabel3.setText("Employee type:");

        jLabel4.setText("Rate Per Day:");

        jLabel5.setText("Hour Per Day:");

        jTextFieldHourPerDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourPerDay1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Number of days worked:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Hourly Worker", "Commission Worker" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextFieldHourPerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourPerDayActionPerformed(evt);
            }
        });

        jTextFieldHourPerDay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourPerDay2ActionPerformed(evt);
            }
        });

        jTextField4.setText("jTextField4");

        jLabel13.setText("Sales:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tax 7% of Monthly Wage:");

        jLabel7.setText("Deductions");

        jCheckBoxSaturday.setText("Saturday");
        jCheckBoxSaturday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaturdayActionPerformed(evt);
            }
        });

        jCheckBoxMonday.setText("Monday");
        jCheckBoxMonday.setToolTipText("");
        jCheckBoxMonday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMondayActionPerformed(evt);
            }
        });

        jCheckBoxThursday.setText("Thursday");
        jCheckBoxThursday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThursdayActionPerformed(evt);
            }
        });

        jCheckBoxSaturday1.setText("Saturday");
        jCheckBoxSaturday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSaturday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaturday1ActionPerformed(evt);
            }
        });

        jCheckBoxWednesday1.setText("Wednesday");
        jCheckBoxWednesday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxWednesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWednesday1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Second week");

        jCheckBoxWednesday.setText("Wednesday");
        jCheckBoxWednesday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWednesdayActionPerformed(evt);
            }
        });

        jCheckBoxFriday1.setText("Friday");
        jCheckBoxFriday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxFriday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFriday1ActionPerformed(evt);
            }
        });

        jLabel11.setText("First week");

        jCheckBoxTuesday.setText("Tuesday");
        jCheckBoxTuesday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTuesdayActionPerformed(evt);
            }
        });

        jCheckBoxTuesday1.setText("Tuesday");
        jCheckBoxTuesday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxTuesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTuesday1ActionPerformed(evt);
            }
        });

        jCheckBoxSunday1.setText("Sunday");
        jCheckBoxSunday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSunday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSunday1ActionPerformed(evt);
            }
        });

        jCheckBoxMonday1.setText("Monday");
        jCheckBoxMonday1.setToolTipText("");
        jCheckBoxMonday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxMonday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMonday1ActionPerformed(evt);
            }
        });

        jCheckBoxFriday.setText("Friday");
        jCheckBoxFriday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFridayActionPerformed(evt);
            }
        });

        jCheckBoxSunday.setText("Sunday");
        jCheckBoxSunday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSundayActionPerformed(evt);
            }
        });

        jCheckBoxThursday1.setText("Thursday");
        jCheckBoxThursday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxThursday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThursday1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxMonday)
                    .addComponent(jLabel11)
                    .addComponent(jCheckBoxWednesday)
                    .addComponent(jCheckBoxFriday)
                    .addComponent(jCheckBoxThursday)
                    .addComponent(jCheckBoxSunday)
                    .addComponent(jCheckBoxTuesday)
                    .addComponent(jCheckBoxSaturday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxWednesday1)
                    .addComponent(jCheckBoxThursday1)
                    .addComponent(jCheckBoxSunday1)
                    .addComponent(jCheckBoxFriday1)
                    .addComponent(jCheckBoxTuesday1)
                    .addComponent(jCheckBoxSaturday1)
                    .addComponent(jCheckBoxMonday1)
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMonday)
                    .addComponent(jCheckBoxMonday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTuesday)
                    .addComponent(jCheckBoxTuesday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxWednesday)
                    .addComponent(jCheckBoxWednesday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxThursday)
                    .addComponent(jCheckBoxThursday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFriday)
                    .addComponent(jCheckBoxFriday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSaturday)
                    .addComponent(jCheckBoxSaturday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSunday)
                    .addComponent(jCheckBoxSunday1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHourPerDay, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHourPerDay2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHourPerDay1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(0, 106, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAddEmployee)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHourPerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldHourPerDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldHourPerDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddEmployee)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 218, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGap(125, 125, 125))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox1, jTextField1, jTextField4, jTextFieldHourPerDay, jTextFieldHourPerDay1, jTextFieldHourPerDay2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddEmployeeActionPerformed

    private void jTextFieldHourPerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourPerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourPerDayActionPerformed

    private void jTextFieldHourPerDay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourPerDay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourPerDay2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldHourPerDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourPerDay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourPerDay1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBoxThursday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThursday1ActionPerformed
        if (jCheckBoxThursday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxThursday1ActionPerformed

    private void jCheckBoxWednesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWednesday1ActionPerformed
        if (jCheckBoxWednesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxWednesday1ActionPerformed

    private void jCheckBoxMonday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMonday1ActionPerformed
        if (jCheckBoxMonday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxMonday1ActionPerformed

    private void jCheckBoxTuesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTuesday1ActionPerformed
        if (jCheckBoxTuesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxTuesday1ActionPerformed

    private void jCheckBoxSunday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSunday1ActionPerformed
        //        if (jCheckBoxSunday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSunday1ActionPerformed

    private void jCheckBoxFriday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFriday1ActionPerformed
        if (jCheckBoxFriday.isSelected()) {
            daysWorked++;
            salary += 8 * hourlyRate;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxFriday1ActionPerformed

    private void jCheckBoxSaturday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaturday1ActionPerformed
        //        if (jCheckBoxSaturday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSaturday1ActionPerformed

    private void jCheckBoxThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThursdayActionPerformed
        if (jCheckBoxThursday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxThursdayActionPerformed

    private void jCheckBoxMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMondayActionPerformed
        if (jCheckBoxMonday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxMondayActionPerformed

    private void jCheckBoxTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTuesdayActionPerformed
        if (jCheckBoxTuesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxTuesdayActionPerformed

    private void jCheckBoxSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaturdayActionPerformed
        //        if (jCheckBoxSaturday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSaturdayActionPerformed

    private void jCheckBoxFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFridayActionPerformed
        if (jCheckBoxFriday.isSelected()) {
            daysWorked++;
            salary += 8 * hourlyRate;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxFridayActionPerformed

    private void jCheckBoxWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWednesdayActionPerformed
        if (jCheckBoxWednesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxWednesdayActionPerformed

    private void jCheckBoxSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSundayActionPerformed
        //        if (jCheckBoxSunday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSundayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewEmployeeEntry dialog = new NewEmployeeEntry(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JCheckBox jCheckBoxFriday;
    private javax.swing.JCheckBox jCheckBoxFriday1;
    private javax.swing.JCheckBox jCheckBoxMonday;
    private javax.swing.JCheckBox jCheckBoxMonday1;
    private javax.swing.JCheckBox jCheckBoxSaturday;
    private javax.swing.JCheckBox jCheckBoxSaturday1;
    private javax.swing.JCheckBox jCheckBoxSunday;
    private javax.swing.JCheckBox jCheckBoxSunday1;
    private javax.swing.JCheckBox jCheckBoxThursday;
    private javax.swing.JCheckBox jCheckBoxThursday1;
    private javax.swing.JCheckBox jCheckBoxTuesday;
    private javax.swing.JCheckBox jCheckBoxTuesday1;
    private javax.swing.JCheckBox jCheckBoxWednesday;
    private javax.swing.JCheckBox jCheckBoxWednesday1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldHourPerDay;
    private javax.swing.JTextField jTextFieldHourPerDay1;
    private javax.swing.JTextField jTextFieldHourPerDay2;
    // End of variables declaration//GEN-END:variables
}
