package payrollsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian AUGUSTYN
 * @duedate
 */
public class PayrollSystemGUI extends javax.swing.JFrame {
    final int MANAGERS_PAYCODE = 1;
    final int HOURLY_WORKERS_PAYCODE = 2;
    final int COMMISSION_WORKERS_PAYCODE = 3;
    final int TAX = 7; // in percentage
    
    private int daysWorked = 0;
    private int hoursWorked = 0;
    private double grossSalary;
    
    Employee employee = new Employee();
    DefaultTableModel model;

    /**
     * Creates new form PayrollSystemGUI
     */
    public PayrollSystemGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEmployeeEntry = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEmpTypeEmpEntry = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEmpNameEmpEntry = new javax.swing.JTextField();
        jButtonSaveEmployee = new javax.swing.JButton();
        jDialogEmployeeDetails = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldRatePerHourEmpDetail = new javax.swing.JTextField();
        jTextFieldDaysWorkedEmpDetail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldEmpNameEmpDetail = new javax.swing.JTextField();
        jTextFieldTotalHoursWorkedEmpDetail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jCheckBoxSaturdayEmpDetailFirstWk = new javax.swing.JCheckBox();
        jCheckBoxMondayEmpDetailFirstWk = new javax.swing.JCheckBox();
        jCheckBoxThursdayEmpDetailFirstWk = new javax.swing.JCheckBox();
        jCheckBoxSaturdayEmpDetailSecondWk = new javax.swing.JCheckBox();
        jCheckBoxWednesdayEmpDetailFirstWk = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jCheckBoxWednesdayEmpDetailSecondWk = new javax.swing.JCheckBox();
        jCheckBoxFridayEmpDetailFirstWk = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jCheckBoxTuesdayEmpDetailFirstWk = new javax.swing.JCheckBox();
        jCheckBoxTuesdayEmpDetailSecondWk = new javax.swing.JCheckBox();
        jCheckBoxSundayEmpDetailFirstWk = new javax.swing.JCheckBox();
        jCheckBoxMondayEmpDetailSecondWk = new javax.swing.JCheckBox();
        jCheckBoxFridayEmpDetailSecondWk = new javax.swing.JCheckBox();
        jCheckBoxSundayEmpDetailSecondWk = new javax.swing.JCheckBox();
        jCheckBoxThursdayEmpDetailSecondWk = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCommissionSalesEmpDetail = new javax.swing.JTextField();
        jTextFieldEmpDetailPayCode = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldTaxMonthlyWageEmpDetail = new javax.swing.JTextField();
        jTextFieldEmpDetailNetSalary = new javax.swing.JTextField();
        jTextFieldEmpDetailDeduction = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldEmpDetailGrossSalary = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonViewPayCheck = new javax.swing.JButton();
        jDialogPayCheck = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        model = new DefaultTableModel();
        jTablePayRoll = new javax.swing.JTable(model);
        jButtonAddEmployee = new javax.swing.JButton();

        jDialogEmployeeEntry.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogEmployeeEntry.setTitle("Employee Entry");
        jDialogEmployeeEntry.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jDialogEmployeeEntry.setModal(true);
        jDialogEmployeeEntry.setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee details"));

        jLabel3.setText("Employee type:");

        jComboBoxEmpTypeEmpEntry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Hourly Worker", "Commission Worker" }));
        jComboBoxEmpTypeEmpEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpTypeEmpEntryActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldEmpNameEmpEntry)
                    .addComponent(jComboBoxEmpTypeEmpEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmpNameEmpEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxEmpTypeEmpEntry)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSaveEmployee.setText("Add Employee");
        jButtonSaveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEmployeeEntryLayout = new javax.swing.GroupLayout(jDialogEmployeeEntry.getContentPane());
        jDialogEmployeeEntry.getContentPane().setLayout(jDialogEmployeeEntryLayout);
        jDialogEmployeeEntryLayout.setHorizontalGroup(
            jDialogEmployeeEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEmployeeEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEmployeeEntryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSaveEmployee)
                .addContainerGap())
        );
        jDialogEmployeeEntryLayout.setVerticalGroup(
            jDialogEmployeeEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEmployeeEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaveEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogEmployeeEntry.getAccessibleContext().setAccessibleDescription("");

        jDialogEmployeeDetails.setTitle("Employee Details");
        jDialogEmployeeDetails.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        jDialogEmployeeDetails.setModal(true);
        jDialogEmployeeDetails.setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee details"));
        jPanel2.setToolTipText("");

        jTextFieldRatePerHourEmpDetail.setText("0");
        jTextFieldRatePerHourEmpDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRatePerHourEmpDetailActionPerformed(evt);
            }
        });

        jTextFieldDaysWorkedEmpDetail.setEditable(false);
        jTextFieldDaysWorkedEmpDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDaysWorkedEmpDetailActionPerformed(evt);
            }
        });

        jLabel14.setText("Rate Per Hour:");

        jLabel15.setText("Total hours worked:");

        jLabel16.setText("Employee name:");

        jLabel17.setText("Pay code:");

        jLabel18.setText("Number of days worked:");

        jTextFieldEmpNameEmpDetail.setEditable(false);

        jTextFieldTotalHoursWorkedEmpDetail.setText("0");
        jTextFieldTotalHoursWorkedEmpDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalHoursWorkedEmpDetailActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Days worked"));

        jCheckBoxSaturdayEmpDetailFirstWk.setText("Saturday");
        jCheckBoxSaturdayEmpDetailFirstWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSaturdayEmpDetailFirstWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaturdayEmpDetailFirstWkActionPerformed(evt);
            }
        });

        jCheckBoxMondayEmpDetailFirstWk.setText("Monday");
        jCheckBoxMondayEmpDetailFirstWk.setToolTipText("");
        jCheckBoxMondayEmpDetailFirstWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxMondayEmpDetailFirstWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMondayEmpDetailFirstWkActionPerformed(evt);
            }
        });

        jCheckBoxThursdayEmpDetailFirstWk.setText("Thursday");
        jCheckBoxThursdayEmpDetailFirstWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxThursdayEmpDetailFirstWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThursdayEmpDetailFirstWkActionPerformed(evt);
            }
        });

        jCheckBoxSaturdayEmpDetailSecondWk.setText("Saturday");
        jCheckBoxSaturdayEmpDetailSecondWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSaturdayEmpDetailSecondWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaturdayEmpDetailSecondWkActionPerformed(evt);
            }
        });

        jCheckBoxWednesdayEmpDetailFirstWk.setText("Wednesday");
        jCheckBoxWednesdayEmpDetailFirstWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxWednesdayEmpDetailFirstWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWednesdayEmpDetailFirstWkActionPerformed(evt);
            }
        });

        jLabel25.setText("Second week");

        jCheckBoxWednesdayEmpDetailSecondWk.setText("Wednesday");
        jCheckBoxWednesdayEmpDetailSecondWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxWednesdayEmpDetailSecondWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWednesdayEmpDetailSecondWkActionPerformed(evt);
            }
        });

        jCheckBoxFridayEmpDetailFirstWk.setText("Friday");
        jCheckBoxFridayEmpDetailFirstWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxFridayEmpDetailFirstWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFridayEmpDetailFirstWkActionPerformed(evt);
            }
        });

        jLabel26.setText("First week");

        jCheckBoxTuesdayEmpDetailFirstWk.setText("Tuesday");
        jCheckBoxTuesdayEmpDetailFirstWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxTuesdayEmpDetailFirstWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTuesdayEmpDetailFirstWkActionPerformed(evt);
            }
        });

        jCheckBoxTuesdayEmpDetailSecondWk.setText("Tuesday");
        jCheckBoxTuesdayEmpDetailSecondWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxTuesdayEmpDetailSecondWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTuesdayEmpDetailSecondWkActionPerformed(evt);
            }
        });

        jCheckBoxSundayEmpDetailFirstWk.setText("Sunday");
        jCheckBoxSundayEmpDetailFirstWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSundayEmpDetailFirstWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSundayEmpDetailFirstWkActionPerformed(evt);
            }
        });

        jCheckBoxMondayEmpDetailSecondWk.setText("Monday");
        jCheckBoxMondayEmpDetailSecondWk.setToolTipText("");
        jCheckBoxMondayEmpDetailSecondWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxMondayEmpDetailSecondWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMondayEmpDetailSecondWkActionPerformed(evt);
            }
        });

        jCheckBoxFridayEmpDetailSecondWk.setText("Friday");
        jCheckBoxFridayEmpDetailSecondWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxFridayEmpDetailSecondWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFridayEmpDetailSecondWkActionPerformed(evt);
            }
        });

        jCheckBoxSundayEmpDetailSecondWk.setText("Sunday");
        jCheckBoxSundayEmpDetailSecondWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSundayEmpDetailSecondWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSundayEmpDetailSecondWkActionPerformed(evt);
            }
        });

        jCheckBoxThursdayEmpDetailSecondWk.setText("Thursday");
        jCheckBoxThursdayEmpDetailSecondWk.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxThursdayEmpDetailSecondWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThursdayEmpDetailSecondWkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxMondayEmpDetailFirstWk)
                    .addComponent(jLabel26)
                    .addComponent(jCheckBoxWednesdayEmpDetailSecondWk)
                    .addComponent(jCheckBoxFridayEmpDetailSecondWk)
                    .addComponent(jCheckBoxThursdayEmpDetailFirstWk)
                    .addComponent(jCheckBoxSundayEmpDetailSecondWk)
                    .addComponent(jCheckBoxTuesdayEmpDetailFirstWk)
                    .addComponent(jCheckBoxSaturdayEmpDetailFirstWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxWednesdayEmpDetailFirstWk)
                    .addComponent(jCheckBoxThursdayEmpDetailSecondWk)
                    .addComponent(jCheckBoxSundayEmpDetailFirstWk)
                    .addComponent(jCheckBoxFridayEmpDetailFirstWk)
                    .addComponent(jCheckBoxTuesdayEmpDetailSecondWk)
                    .addComponent(jCheckBoxSaturdayEmpDetailSecondWk)
                    .addComponent(jCheckBoxMondayEmpDetailSecondWk)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMondayEmpDetailFirstWk)
                    .addComponent(jCheckBoxMondayEmpDetailSecondWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTuesdayEmpDetailFirstWk)
                    .addComponent(jCheckBoxTuesdayEmpDetailSecondWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxWednesdayEmpDetailSecondWk)
                    .addComponent(jCheckBoxWednesdayEmpDetailFirstWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxThursdayEmpDetailFirstWk)
                    .addComponent(jCheckBoxThursdayEmpDetailSecondWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFridayEmpDetailSecondWk)
                    .addComponent(jCheckBoxFridayEmpDetailFirstWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSaturdayEmpDetailFirstWk)
                    .addComponent(jCheckBoxSaturdayEmpDetailSecondWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSundayEmpDetailSecondWk)
                    .addComponent(jCheckBoxSundayEmpDetailFirstWk))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setText("Sales:");

        jTextFieldCommissionSalesEmpDetail.setText("0");
        jTextFieldCommissionSalesEmpDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCommissionSalesEmpDetailActionPerformed(evt);
            }
        });

        jTextFieldEmpDetailPayCode.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmpNameEmpDetail)
                    .addComponent(jTextFieldTotalHoursWorkedEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDaysWorkedEmpDetail)
                    .addComponent(jTextFieldRatePerHourEmpDetail)
                    .addComponent(jTextFieldCommissionSalesEmpDetail)
                    .addComponent(jTextFieldEmpDetailPayCode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmpNameEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldEmpDetailPayCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCommissionSalesEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldRatePerHourEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldTotalHoursWorkedEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldDaysWorkedEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Deductions"));

        jLabel24.setText("Tax of Monthly Wage:");

        jTextFieldTaxMonthlyWageEmpDetail.setText("7");
        jTextFieldTaxMonthlyWageEmpDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaxMonthlyWageEmpDetailActionPerformed(evt);
            }
        });

        jTextFieldEmpDetailNetSalary.setEditable(false);

        jTextFieldEmpDetailDeduction.setEditable(false);

        jLabel22.setText("Net Salary:");

        jLabel23.setText("Gross Salary:");

        jTextFieldEmpDetailGrossSalary.setEditable(false);
        jTextFieldEmpDetailGrossSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpDetailGrossSalaryActionPerformed(evt);
            }
        });

        jLabel21.setText("Total Deduction:");

        jLabel6.setText("%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmpDetailGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmpDetailNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldTaxMonthlyWageEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEmpDetailDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldTaxMonthlyWageEmpDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmpDetailGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldEmpDetailDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldEmpDetailNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButtonViewPayCheck.setText("Calculate pay");
        jButtonViewPayCheck.setToolTipText("");
        jButtonViewPayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewPayCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEmployeeDetailsLayout = new javax.swing.GroupLayout(jDialogEmployeeDetails.getContentPane());
        jDialogEmployeeDetails.getContentPane().setLayout(jDialogEmployeeDetailsLayout);
        jDialogEmployeeDetailsLayout.setHorizontalGroup(
            jDialogEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEmployeeDetailsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDialogEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEmployeeDetailsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEmployeeDetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonViewPayCheck)))
                .addContainerGap())
        );
        jDialogEmployeeDetailsLayout.setVerticalGroup(
            jDialogEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEmployeeDetailsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jDialogEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEmployeeDetailsLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jDialogEmployeeDetailsLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonViewPayCheck)))
                .addContainerGap())
        );

        jDialogPayCheck.setTitle("Pay Check");
        jDialogPayCheck.setBackground(new java.awt.Color(255, 204, 51));
        jDialogPayCheck.setBounds(new java.awt.Rectangle(0, 0, 340, 430));
        jDialogPayCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogPayCheck.setModal(true);
        jDialogPayCheck.setResizable(false);

        javax.swing.GroupLayout jDialogPayCheckLayout = new javax.swing.GroupLayout(jDialogPayCheck.getContentPane());
        jDialogPayCheck.getContentPane().setLayout(jDialogPayCheckLayout);
        jDialogPayCheckLayout.setHorizontalGroup(
            jDialogPayCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jDialogPayCheckLayout.setVerticalGroup(
            jDialogPayCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payroll System");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jTablePayRoll.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        // jTablePayRoll.setModel(new javax.swing.table.DefaultTableModel(
        //     new Object [][] {
        //         {null, null, null, null},
        //         {null, null, null, null},
        //         {null, null, null, null},
        //         {null, null, null, null}
        //     },
        //     new String [] {
        //         "Title 1", "Title 2", "Title 3", "Title 4"
        //     }
        // ) {
        //     boolean[] canEdit = new boolean [] {
        //         false, false, false, false
        //     };

        //     public boolean isCellEditable(int rowIndex, int columnIndex) {
        //         return canEdit [columnIndex];
        //     }
        // });
        // String[][] rec = {
        //     { "1", "Steve", "AUS" },
        //     { "2", "Virat", "IND" },
        //     { "3", "Kane", "NZ" },
        //     { "4", "David", "AUS" },
        //     { "5", "Ben", "ENG" },
        //     { "6", "Eion", "ENG" }
        // };
        model.addColumn("Employee name");
        model.addColumn("Pay code");
        model.addColumn("Employee type");
        // Append a row
        // model.addRow(rec);

        jTablePayRoll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePayRollMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePayRoll);

        jButtonAddEmployee.setText("+ Add employee");
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddEmployee))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEmployeeActionPerformed
        jDialogEmployeeEntry.pack();
        jDialogEmployeeEntry.setVisible(true);
    }//GEN-LAST:event_jButtonAddEmployeeActionPerformed

    private void jButtonSaveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveEmployeeActionPerformed
        // TODO add your handling code here:
//        Object selectedItem = jComboBoxEmpTypeEmpEntry.getSelectedItem();
        int selectedIndex = jComboBoxEmpTypeEmpEntry.getSelectedIndex();
        switch (selectedIndex+1) {
            case MANAGERS_PAYCODE:
                employee.setPayCode(MANAGERS_PAYCODE);
                break;
            case HOURLY_WORKERS_PAYCODE:
                employee.setPayCode(HOURLY_WORKERS_PAYCODE);
                break;
            case COMMISSION_WORKERS_PAYCODE:
                employee.setPayCode(COMMISSION_WORKERS_PAYCODE);
                break;
        }
        employee.setName(jTextFieldEmpNameEmpEntry.getText());
        if (employee.getPayCode() == 1) {
            String[] rec = { employee.getName(), String.format("%d", employee.getPayCode()), "Manager"};
            model.addRow(rec);
        }
        else if (employee.getPayCode() == 2) {
            String[] rec = { employee.getName(), String.format("%d", employee.getPayCode()), "Hourly Worker"};
            model.addRow(rec);
        }
        else if (employee.getPayCode() == 3) {
            String[] rec = { employee.getName(), String.format("%d", employee.getPayCode()), "Commission Worker"};
            model.addRow(rec);
        }
        jDialogEmployeeEntry.dispose();
    }//GEN-LAST:event_jButtonSaveEmployeeActionPerformed

    private void jTablePayRollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePayRollMouseClicked
        // clear fields for new employee details
        jTextFieldCommissionSalesEmpDetail.setText(String.format("%.2f", 0.0));                                           
        jTextFieldRatePerHourEmpDetail.setText(String.format("%.2f", 0.0));
        jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%.2f", 0.0));                                           
        jTextFieldDaysWorkedEmpDetail.setText(String.format("%.2f", 0.0));
        jTextFieldEmpDetailGrossSalary.setText(String.format("%.2f", 0.0));
        jTextFieldEmpDetailDeduction.setText(String.format("%.2f", 0.0));
        jTextFieldEmpDetailNetSalary.setText(String.format("%.2f", 0.0)); 
        jCheckBoxSundayEmpDetailFirstWk.setSelected(false);
        jCheckBoxMondayEmpDetailFirstWk.setSelected(false);
        jCheckBoxTuesdayEmpDetailFirstWk.setSelected(false);
        jCheckBoxWednesdayEmpDetailFirstWk.setSelected(false);
        jCheckBoxThursdayEmpDetailFirstWk.setSelected(false);
        jCheckBoxFridayEmpDetailFirstWk.setSelected(false);
        jCheckBoxSaturdayEmpDetailFirstWk.setSelected(false);
        jCheckBoxSundayEmpDetailSecondWk.setSelected(false);
        jCheckBoxMondayEmpDetailSecondWk.setSelected(false);
        jCheckBoxTuesdayEmpDetailSecondWk.setSelected(false);
        jCheckBoxWednesdayEmpDetailSecondWk.setSelected(false);
        jCheckBoxThursdayEmpDetailSecondWk.setSelected(false);
        jCheckBoxFridayEmpDetailSecondWk.setSelected(false);
        jCheckBoxSaturdayEmpDetailSecondWk.setSelected(false);
        
        // set epployee details
        jTextFieldEmpNameEmpDetail.setText(employee.getName());                                           
        jTextFieldEmpDetailPayCode.setText(String.format("%d", employee.getPayCode()));
        if (employee.getPayCode() == MANAGERS_PAYCODE) {
            jTextFieldCommissionSalesEmpDetail.setEnabled(false);
            jTextFieldRatePerHourEmpDetail.setEnabled(true);
            jTextFieldTotalHoursWorkedEmpDetail.setEnabled(false);
            jTextFieldCommissionSalesEmpDetail.setEditable(false);
            jTextFieldRatePerHourEmpDetail.setEditable(true);
            jTextFieldTotalHoursWorkedEmpDetail.setEditable(false);
            
            jCheckBoxSundayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxMondayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxTuesdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxWednesdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxThursdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxFridayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxSaturdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxSundayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxMondayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxTuesdayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxWednesdayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxThursdayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxFridayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxSaturdayEmpDetailSecondWk.setEnabled(false); 
        }
        // if employee is a Hourly worker
        else if (employee.getPayCode() == HOURLY_WORKERS_PAYCODE) {
            jTextFieldCommissionSalesEmpDetail.setEnabled(false);
            jTextFieldRatePerHourEmpDetail.setEnabled(true);
            jTextFieldTotalHoursWorkedEmpDetail.setEnabled(true);
            jTextFieldCommissionSalesEmpDetail.setEditable(false);
            jTextFieldRatePerHourEmpDetail.setEditable(true);
            jTextFieldTotalHoursWorkedEmpDetail.setEditable(true);
            
            jCheckBoxSundayEmpDetailFirstWk.setEnabled(true);
            jCheckBoxMondayEmpDetailFirstWk.setEnabled(true);
            jCheckBoxTuesdayEmpDetailFirstWk.setEnabled(true);
            jCheckBoxWednesdayEmpDetailFirstWk.setEnabled(true);
            jCheckBoxThursdayEmpDetailFirstWk.setEnabled(true);
            jCheckBoxFridayEmpDetailFirstWk.setEnabled(true);
            jCheckBoxSaturdayEmpDetailFirstWk.setEnabled(true);
            jCheckBoxSundayEmpDetailSecondWk.setEnabled(true);
            jCheckBoxMondayEmpDetailSecondWk.setEnabled(true);
            jCheckBoxTuesdayEmpDetailSecondWk.setEnabled(true);
            jCheckBoxWednesdayEmpDetailSecondWk.setEnabled(true);
            jCheckBoxThursdayEmpDetailSecondWk.setEnabled(true);
            jCheckBoxFridayEmpDetailSecondWk.setEnabled(true);
            jCheckBoxSaturdayEmpDetailSecondWk.setEnabled(true);
        }
        else if (employee.getPayCode() == COMMISSION_WORKERS_PAYCODE) {
            jTextFieldCommissionSalesEmpDetail.setEnabled(true);
            jTextFieldRatePerHourEmpDetail.setEnabled(false);
            jTextFieldTotalHoursWorkedEmpDetail.setEnabled(false);
            jTextFieldCommissionSalesEmpDetail.setEditable(true);
            jTextFieldRatePerHourEmpDetail.setEditable(false);
            jTextFieldTotalHoursWorkedEmpDetail.setEditable(false);
            
            jCheckBoxSundayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxMondayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxTuesdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxWednesdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxThursdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxFridayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxSaturdayEmpDetailFirstWk.setEnabled(false);
            jCheckBoxSundayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxMondayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxTuesdayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxWednesdayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxThursdayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxFridayEmpDetailSecondWk.setEnabled(false);
            jCheckBoxSaturdayEmpDetailSecondWk.setEnabled(false);
        }

        // check for selected row first
//         if(jTablePayRoll.getSelectedRow() != -1) {
//            // remove selected row from the model
// //               model.removeRow(jTablePayRoll.getSelectedRow());
//            JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
//         }

        jDialogEmployeeDetails.pack();
        jDialogEmployeeDetails.setVisible(true);
    }//GEN-LAST:event_jTablePayRollMouseClicked
    
    private void jComboBoxEmpTypeEmpEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpTypeEmpEntryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxEmpTypeEmpEntryActionPerformed

    private void jTextFieldRatePerHourEmpDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRatePerHourEmpDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRatePerHourEmpDetailActionPerformed

    private void jTextFieldDaysWorkedEmpDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDaysWorkedEmpDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDaysWorkedEmpDetailActionPerformed

    private void jTextFieldTotalHoursWorkedEmpDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalHoursWorkedEmpDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalHoursWorkedEmpDetailActionPerformed

    private void jTextFieldTaxMonthlyWageEmpDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaxMonthlyWageEmpDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaxMonthlyWageEmpDetailActionPerformed

    private void jCheckBoxSaturdayEmpDetailFirstWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaturdayEmpDetailFirstWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxSaturdayEmpDetailFirstWk.isSelected()) {
                daysWorked++;
                grossSalary += 1.5 * hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= 1.5 * hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxSaturdayEmpDetailFirstWkActionPerformed

    private void jCheckBoxMondayEmpDetailFirstWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMondayEmpDetailFirstWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxMondayEmpDetailFirstWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxMondayEmpDetailFirstWkActionPerformed

    private void jCheckBoxThursdayEmpDetailFirstWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThursdayEmpDetailFirstWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxThursdayEmpDetailFirstWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxThursdayEmpDetailFirstWkActionPerformed

    private void jCheckBoxSaturdayEmpDetailSecondWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaturdayEmpDetailSecondWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxSaturdayEmpDetailSecondWk.isSelected()) {
                daysWorked++;
                grossSalary += 1.5 * hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= 1.5 * hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
            } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxSaturdayEmpDetailSecondWkActionPerformed

    private void jCheckBoxWednesdayEmpDetailFirstWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWednesdayEmpDetailFirstWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxWednesdayEmpDetailFirstWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxWednesdayEmpDetailFirstWkActionPerformed

    private void jCheckBoxWednesdayEmpDetailSecondWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWednesdayEmpDetailSecondWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxWednesdayEmpDetailSecondWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxWednesdayEmpDetailSecondWkActionPerformed

    private void jCheckBoxFridayEmpDetailFirstWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFridayEmpDetailFirstWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxFridayEmpDetailFirstWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxFridayEmpDetailFirstWkActionPerformed

    private void jCheckBoxTuesdayEmpDetailFirstWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTuesdayEmpDetailFirstWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxTuesdayEmpDetailFirstWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxTuesdayEmpDetailFirstWkActionPerformed

    private void jCheckBoxTuesdayEmpDetailSecondWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTuesdayEmpDetailSecondWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxTuesdayEmpDetailSecondWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
               grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxTuesdayEmpDetailSecondWkActionPerformed

    private void jCheckBoxSundayEmpDetailFirstWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSundayEmpDetailFirstWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxSundayEmpDetailFirstWk.isSelected()) {
                daysWorked++;
                grossSalary += 2 * hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= 2 * hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxSundayEmpDetailFirstWkActionPerformed

    private void jCheckBoxMondayEmpDetailSecondWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMondayEmpDetailSecondWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxMondayEmpDetailSecondWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxMondayEmpDetailSecondWkActionPerformed

    private void jCheckBoxFridayEmpDetailSecondWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFridayEmpDetailSecondWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxFridayEmpDetailSecondWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxFridayEmpDetailSecondWkActionPerformed

    private void jCheckBoxSundayEmpDetailSecondWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSundayEmpDetailSecondWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxSundayEmpDetailSecondWk.isSelected()) {
                daysWorked++;
                grossSalary += 2 * hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= 2 * hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxSundayEmpDetailSecondWkActionPerformed

    private void jCheckBoxThursdayEmpDetailSecondWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThursdayEmpDetailSecondWkActionPerformed
        // TODO add your handling code here:
        double hourlyRate = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
        if (hourlyRate > 0) {
            if (jCheckBoxThursdayEmpDetailSecondWk.isSelected()) {
                daysWorked++;
                grossSalary += hourlyRate * 8;
            } else {
                daysWorked--;
                grossSalary -= hourlyRate * 8;
            }
            hoursWorked = daysWorked * 8;
            jTextFieldTotalHoursWorkedEmpDetail.setText(String.format("%d", hoursWorked));
            jTextFieldDaysWorkedEmpDetail.setText(String.format("%d", daysWorked));
        } 
        else {
            JOptionPane.showMessageDialog(null, 
                    "No hourly rate", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxThursdayEmpDetailSecondWkActionPerformed

    private void jTextFieldCommissionSalesEmpDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCommissionSalesEmpDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCommissionSalesEmpDetailActionPerformed

    private void jTextFieldEmpDetailGrossSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpDetailGrossSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpDetailGrossSalaryActionPerformed

    private void jButtonViewPayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewPayCheckActionPerformed
        // TODO add your handling code here:
        double tax = Double.parseDouble(jTextFieldTaxMonthlyWageEmpDetail.getText());
        
        if (employee.getPayCode() == MANAGERS_PAYCODE) {
            jTextFieldRatePerHourEmpDetail.setText(String.format("%.2f", 11.38));
            double ratePerHour = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
            grossSalary = ratePerHour * 8 * 14;
            double deduc = (tax/(double)100) * grossSalary;
            double salary = 250 + (5.7/(double)100) * grossSalary;
            double netSalary = salary - deduc;
            
            jTextFieldEmpDetailGrossSalary.setText(String.format("%.2f", salary));
            jTextFieldEmpDetailDeduction.setText(String.format("%.2f", deduc));
            jTextFieldEmpDetailNetSalary.setText(String.format("%.2f", netSalary));            
        }
        // if employee is a Hourly worker
        else if (employee.getPayCode() == HOURLY_WORKERS_PAYCODE) {
            double ratePerHour = Double.parseDouble(jTextFieldRatePerHourEmpDetail.getText());
//            double hoursWorked = Double.parseDouble(jTextFieldTotalHoursWorkedEmpDetail.getText());
//            grossSalary += ratePerHour * hoursWorked;
            double deduc = (tax/(double)100) * grossSalary;
            double netSalary = grossSalary - deduc;
            
            jTextFieldEmpDetailGrossSalary.setText(String.format("%.2f", grossSalary));
            jTextFieldEmpDetailDeduction.setText(String.format("%.2f", deduc));
            jTextFieldEmpDetailNetSalary.setText(String.format("%.2f", netSalary));
        }
        else if (employee.getPayCode() == COMMISSION_WORKERS_PAYCODE) {
            double sales = Double.parseDouble(jTextFieldCommissionSalesEmpDetail.getText());
            double deduc = (tax/(double)100) * sales;
            double salary = 250 + (5.7/(double)100) * sales;
            double netSalary = salary - deduc;
            
            jTextFieldEmpDetailGrossSalary.setText(String.format("%.2f", salary));
            jTextFieldEmpDetailDeduction.setText(String.format("%.2f", deduc));
            jTextFieldEmpDetailNetSalary.setText(String.format("%.2f", netSalary));
        }
    }//GEN-LAST:event_jButtonViewPayCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollSystemGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JButton jButtonSaveEmployee;
    private javax.swing.JButton jButtonViewPayCheck;
    private javax.swing.JCheckBox jCheckBoxFridayEmpDetailFirstWk;
    private javax.swing.JCheckBox jCheckBoxFridayEmpDetailSecondWk;
    private javax.swing.JCheckBox jCheckBoxMondayEmpDetailFirstWk;
    private javax.swing.JCheckBox jCheckBoxMondayEmpDetailSecondWk;
    private javax.swing.JCheckBox jCheckBoxSaturdayEmpDetailFirstWk;
    private javax.swing.JCheckBox jCheckBoxSaturdayEmpDetailSecondWk;
    private javax.swing.JCheckBox jCheckBoxSundayEmpDetailFirstWk;
    private javax.swing.JCheckBox jCheckBoxSundayEmpDetailSecondWk;
    private javax.swing.JCheckBox jCheckBoxThursdayEmpDetailFirstWk;
    private javax.swing.JCheckBox jCheckBoxThursdayEmpDetailSecondWk;
    private javax.swing.JCheckBox jCheckBoxTuesdayEmpDetailFirstWk;
    private javax.swing.JCheckBox jCheckBoxTuesdayEmpDetailSecondWk;
    private javax.swing.JCheckBox jCheckBoxWednesdayEmpDetailFirstWk;
    private javax.swing.JCheckBox jCheckBoxWednesdayEmpDetailSecondWk;
    private javax.swing.JComboBox jComboBoxEmpTypeEmpEntry;
    private javax.swing.JDialog jDialogEmployeeDetails;
    private javax.swing.JDialog jDialogEmployeeEntry;
    private javax.swing.JDialog jDialogPayCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePayRoll;
    private javax.swing.JTextField jTextFieldCommissionSalesEmpDetail;
    private javax.swing.JTextField jTextFieldDaysWorkedEmpDetail;
    private javax.swing.JTextField jTextFieldEmpDetailDeduction;
    private javax.swing.JTextField jTextFieldEmpDetailGrossSalary;
    private javax.swing.JTextField jTextFieldEmpDetailNetSalary;
    private javax.swing.JTextField jTextFieldEmpDetailPayCode;
    private javax.swing.JTextField jTextFieldEmpNameEmpDetail;
    private javax.swing.JTextField jTextFieldEmpNameEmpEntry;
    private javax.swing.JTextField jTextFieldRatePerHourEmpDetail;
    private javax.swing.JTextField jTextFieldTaxMonthlyWageEmpDetail;
    private javax.swing.JTextField jTextFieldTotalHoursWorkedEmpDetail;
    // End of variables declaration//GEN-END:variables
}
