package payrollsystem;

import java.awt.event.ActionEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian AUGUSTYN
 */
public class ViewWorker extends javax.swing.JDialog {
    private int daysWorked;
    private int hourlyRate;
    private int salary;

    /**
     * Creates new form ViewWorker2
     */
    public ViewWorker(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonViewPayCheck = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldRatePerDay = new javax.swing.JTextField();
        jTextFieldDaysWorked = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextFieldHourPerDay = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxSunday = new javax.swing.JCheckBox();
        jCheckBoxSunday1 = new javax.swing.JCheckBox();
        jCheckBoxThursday1 = new javax.swing.JCheckBox();
        jCheckBoxFriday = new javax.swing.JCheckBox();
        jCheckBoxWednesday = new javax.swing.JCheckBox();
        jCheckBoxThursday = new javax.swing.JCheckBox();
        jCheckBoxSaturday1 = new javax.swing.JCheckBox();
        jCheckBoxMonday1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jCheckBoxSaturday = new javax.swing.JCheckBox();
        jCheckBoxTuesday = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxMonday = new javax.swing.JCheckBox();
        jCheckBoxTuesday1 = new javax.swing.JCheckBox();
        jCheckBoxWednesday1 = new javax.swing.JCheckBox();
        jCheckBoxFriday1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonAddEmployee = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonCalculatePay = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Employee");

        jButtonViewPayCheck.setText("View Paycheck");
        jButtonViewPayCheck.setToolTipText("");
        jButtonViewPayCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewPayCheckActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee details"));
        jPanel2.setToolTipText("");

        jTextFieldRatePerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRatePerDayActionPerformed(evt);
            }
        });

        jTextFieldDaysWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDaysWorkedActionPerformed(evt);
            }
        });

        jLabel4.setText("Rate Per Day:");

        jLabel5.setText("Hour Per Day:");

        jLabel2.setText("Employee name:");

        jLabel3.setText("Employee type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Hourly Worker", "Commission Worker" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Number of days worked:");

        jTextFieldHourPerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourPerDayActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Days worked"));

        jCheckBoxSunday.setText("Sunday");
        jCheckBoxSunday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSundayActionPerformed(evt);
            }
        });

        jCheckBoxSunday1.setText("Sunday");
        jCheckBoxSunday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSunday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSunday1ActionPerformed(evt);
            }
        });

        jCheckBoxThursday1.setText("Thursday");
        jCheckBoxThursday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxThursday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThursday1ActionPerformed(evt);
            }
        });

        jCheckBoxFriday.setText("Friday");
        jCheckBoxFriday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFridayActionPerformed(evt);
            }
        });

        jCheckBoxWednesday.setText("Wednesday");
        jCheckBoxWednesday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWednesdayActionPerformed(evt);
            }
        });

        jCheckBoxThursday.setText("Thursday");
        jCheckBoxThursday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThursdayActionPerformed(evt);
            }
        });

        jCheckBoxSaturday1.setText("Saturday");
        jCheckBoxSaturday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSaturday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaturday1ActionPerformed(evt);
            }
        });

        jCheckBoxMonday1.setText("Monday");
        jCheckBoxMonday1.setToolTipText("");
        jCheckBoxMonday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxMonday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMonday1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Second week");

        jCheckBoxSaturday.setText("Saturday");
        jCheckBoxSaturday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaturdayActionPerformed(evt);
            }
        });

        jCheckBoxTuesday.setText("Tuesday");
        jCheckBoxTuesday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTuesdayActionPerformed(evt);
            }
        });

        jLabel1.setText("First week");

        jCheckBoxMonday.setText("Monday");
        jCheckBoxMonday.setToolTipText("");
        jCheckBoxMonday.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMondayActionPerformed(evt);
            }
        });

        jCheckBoxTuesday1.setText("Tuesday");
        jCheckBoxTuesday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxTuesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTuesday1ActionPerformed(evt);
            }
        });

        jCheckBoxWednesday1.setText("Wednesday");
        jCheckBoxWednesday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxWednesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWednesday1ActionPerformed(evt);
            }
        });

        jCheckBoxFriday1.setText("Friday");
        jCheckBoxFriday1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCheckBoxFriday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFriday1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxMonday)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxWednesday)
                    .addComponent(jCheckBoxFriday)
                    .addComponent(jCheckBoxThursday)
                    .addComponent(jCheckBoxSunday)
                    .addComponent(jCheckBoxTuesday)
                    .addComponent(jCheckBoxSaturday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxWednesday1)
                    .addComponent(jCheckBoxThursday1)
                    .addComponent(jCheckBoxSunday1)
                    .addComponent(jCheckBoxFriday1)
                    .addComponent(jCheckBoxTuesday1)
                    .addComponent(jCheckBoxSaturday1)
                    .addComponent(jCheckBoxMonday1)
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMonday)
                    .addComponent(jCheckBoxMonday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTuesday)
                    .addComponent(jCheckBoxTuesday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxWednesday)
                    .addComponent(jCheckBoxWednesday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxThursday)
                    .addComponent(jCheckBoxThursday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFriday)
                    .addComponent(jCheckBoxFriday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSaturday)
                    .addComponent(jCheckBoxSaturday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSunday)
                    .addComponent(jCheckBoxSunday1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDaysWorked, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldRatePerDay)
                            .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldHourPerDay)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldRatePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldHourPerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Gross Salary");

        jTextField4.setText("jTextField3");

        jLabel10.setText("Net Salary");

        jButtonAddEmployee.setText("Edit details");
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEmployeeActionPerformed(evt);
            }
        });

        jLabel11.setText("Total Deduction");

        jButtonCalculatePay.setText("Calculate Pay");
        jButtonCalculatePay.setToolTipText("");
        jButtonCalculatePay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculatePayActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Deductions"));

        jLabel8.setText("Tax 7% of Monthly Wage:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonViewPayCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCalculatePay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddEmployee))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddEmployee)
                    .addComponent(jButtonCalculatePay)
                    .addComponent(jButtonViewPayCheck))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThursdayActionPerformed
        if (jCheckBoxThursday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxThursdayActionPerformed

    private void jCheckBoxTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTuesdayActionPerformed
        if (jCheckBoxTuesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxTuesdayActionPerformed

    private void jCheckBoxSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSundayActionPerformed
        //        if (jCheckBoxSunday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSundayActionPerformed

    private void jCheckBoxSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaturdayActionPerformed
        //        if (jCheckBoxSaturday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSaturdayActionPerformed

    private void jCheckBoxFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFridayActionPerformed
        if (jCheckBoxFriday.isSelected()) {
            daysWorked++;
            salary += 8 * hourlyRate;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxFridayActionPerformed

    private void jButtonCalculatePayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculatePayActionPerformed
        if (jCheckBoxMonday.isSelected() ||
            jCheckBoxTuesday.isSelected() ||
            jCheckBoxWednesday.isSelected() ||
            jCheckBoxThursday.isSelected() ||
            jCheckBoxFriday.isSelected()) {
            salary = 8 * daysWorked * hourlyRate;

        }
        if (jCheckBoxSaturday.isSelected()) {
            salary += 8 * (hourlyRate/2);
        }
        if (jCheckBoxSunday.isSelected()) {
            salary += 8 * (hourlyRate*2);
        }
        System.out.println("Your salary is " + daysWorked);
        //        JOptionPane.showMessageDialog(this, "Eeerr", null, WIDTH, null);
     }//GEN-LAST:event_jButtonCalculatePayActionPerformed
    
    private void jButtonViewPayCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewPayCheckActionPerformed
//        paycheck.setVisible(true);
//        JOptionPane.showMessageDialog(this, "Eeerr", null, WIDTH, null);
     }//GEN-LAST:event_jButtonViewPayCheckActionPerformed
    
    private void jCheckBoxMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMondayActionPerformed
        if (jCheckBoxMonday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxMondayActionPerformed

    private void jCheckBoxWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWednesdayActionPerformed
        if (jCheckBoxWednesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxWednesdayActionPerformed

    private void jTextFieldRatePerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRatePerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRatePerDayActionPerformed

    private void jTextFieldDaysWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDaysWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDaysWorkedActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        System.out.println(evt);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldHourPerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourPerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourPerDayActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddEmployeeActionPerformed

    private void jCheckBoxThursday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThursday1ActionPerformed
        if (jCheckBoxThursday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxThursday1ActionPerformed

    private void jCheckBoxWednesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWednesday1ActionPerformed
        if (jCheckBoxWednesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxWednesday1ActionPerformed

    private void jCheckBoxTuesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTuesday1ActionPerformed
        if (jCheckBoxTuesday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxTuesday1ActionPerformed

    private void jCheckBoxSunday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSunday1ActionPerformed
        //        if (jCheckBoxSunday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSunday1ActionPerformed

    private void jCheckBoxMonday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMonday1ActionPerformed
        if (jCheckBoxMonday.isSelected()) {
            daysWorked++;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxMonday1ActionPerformed

    private void jCheckBoxSaturday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaturday1ActionPerformed
        //        if (jCheckBoxSaturday.isSelected()) {
            //            daysWorked++;
            //        } else {
            //            daysWorked--;
            //        }
    }//GEN-LAST:event_jCheckBoxSaturday1ActionPerformed

    private void jCheckBoxFriday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFriday1ActionPerformed
        if (jCheckBoxFriday.isSelected()) {
            daysWorked++;
            salary += 8 * hourlyRate;
        } else {
            daysWorked--;
        }
    }//GEN-LAST:event_jCheckBoxFriday1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewWorker dialog = new ViewWorker(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JButton jButtonCalculatePay;
    private javax.swing.JButton jButtonViewPayCheck;
    private javax.swing.JCheckBox jCheckBoxFriday;
    private javax.swing.JCheckBox jCheckBoxFriday1;
    private javax.swing.JCheckBox jCheckBoxMonday;
    private javax.swing.JCheckBox jCheckBoxMonday1;
    private javax.swing.JCheckBox jCheckBoxSaturday;
    private javax.swing.JCheckBox jCheckBoxSaturday1;
    private javax.swing.JCheckBox jCheckBoxSunday;
    private javax.swing.JCheckBox jCheckBoxSunday1;
    private javax.swing.JCheckBox jCheckBoxThursday;
    private javax.swing.JCheckBox jCheckBoxThursday1;
    private javax.swing.JCheckBox jCheckBoxTuesday;
    private javax.swing.JCheckBox jCheckBoxTuesday1;
    private javax.swing.JCheckBox jCheckBoxWednesday;
    private javax.swing.JCheckBox jCheckBoxWednesday1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldDaysWorked;
    private javax.swing.JTextField jTextFieldHourPerDay;
    private javax.swing.JTextField jTextFieldRatePerDay;
    // End of variables declaration//GEN-END:variables
}
